services:
    Netliva\FileTypeBundle\Service\UploadHelperService:
        class: Netliva\FileTypeBundle\Service\UploadHelperService
        public: false
        arguments: [ "@service_container",  '@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    netliva.file.upload_helper:
        alias: Netliva\FileTypeBundle\Service\UploadHelperService
        public: true

    netliva.file_type:
        class: Netliva\FileTypeBundle\Form\Type\NetlivaFileType
        arguments: [ "@netliva.file.upload_helper" ]
        tags:
            - { name: form.type }

    netliva.file_loader:
        class: Netliva\FileTypeBundle\Routing\FileLoader
        arguments: [ "@service_container"]
        tags:
            - { name: routing.loader }


